---
- hosts: all
  become: true
  vars:
    http_port: 80
    domain: example.com

  tasks:
    - name: "update apt packages"
      become: true
      become_method: sudo
      apt:
        update_cache: yes

    - name: set hostname
      command: |
        sudo hostnamectl set-hostname mini-project
  
    - name: set timezone to lagos
      command: |
        sudo timedatectl set-timezone Africa/Lagos

    - name: install packages
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - apache2
        - git

    - name: ensure apache2 started
      service: name=apache2 state=started enabled=yes

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
      notify:
        - restart apache2

    - name: apache2 listen on port 80
      lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen " line="Listen 80" state=present
      notify:
        - restart apache2

    - name: apache2 virtualhost on port 80
      lineinfile: dest=/etc/apache2/sites-available/000-default.conf regexp="^<VirtualHost \*:" line="<VirtualHost *:80>"
      notify:
        - restart apache2

    - name: create virtual host file
      template: src=virtualhost.conf dest=/etc/apache2/sites-available/mini-project.conf

    - name: a2ensite mini-project
      command: a2ensite mini-project
      args:
        creates: /etc/apache2/sites-enabled/mini-project.conf
      notify:
        - restart apache2

    - name: clone basic html template
      git: repo=https://github.com/do-community/ansible-apache-tutorial.git dest=/var/www/mini-project update=no

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted